import photo1 from '../../../../../public/photo-1.jpg'
import photo2 from '../../../../../public/photo-2.jpg'
import photo3 from '../../../../../public/photo-3.jpg'

export const itemList = [
  {id: 1, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: 'New'},
  {id: 2, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: 'New'},
  {id: 3, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: 'New'},
  {id: 4, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: ['New', 'Popular'],},
  {id: 5, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: ['New', 'Popular'],},
  {id: 6, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: ['New', 'Popular'],},
  {id: 7, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: 'Rare'},
  {id: 8, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: ['New', 'Rare'],},
  {id: 9, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo1, cat: ['New', 'Rare'],},
  {id: 11, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'Rare'],},
  {id: 12, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'Rare'],},
  {id: 13, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'Rare'],},
  {id: 14, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'Hot'],},
  {id: 15, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'Rare'],},
  {id: 16, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'Rare'],},
  {id: 17, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'Rare'],},
  {id: 18, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo2, cat: ['New', 'RHot'],},
  {id: 19, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Hot'],},
  {id: 20, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Rare'],},
  {id: 21, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Hot'],},
  {id: 22, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Rare'],},
  {id: 23, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Rare'],},
  {id: 24, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Rare'],},
  {id: 25, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['Hot', 'Rare'],},
  {id: 26, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Rare'],},
  {id: 27, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Hot'],},
  {id: 28, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['Hot', 'Rare'],},
  {id: 29, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Rare'],},
  {id: 30, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['New', 'Rare'],},
  {id: 31, title: 'item', description: 'itemDescription', price: 10.5, imageUrl: photo3, cat: ['Hot', 'Rare'],},
]